//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionShares.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LionShares.Localization.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept
        {
            get
            {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin
        {
            get
            {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin Mode.
        /// </summary>
        public static string AdminMode
        {
            get
            {
                return ResourceManager.GetString("AdminMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are {0} an admin..
        /// </summary>
        public static string AdminModeMessageText
        {
            get
            {
                return ResourceManager.GetString("AdminModeMessageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        public static string AppInfo
        {
            get
            {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply
        {
            get
            {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Management.
        /// </summary>
        public static string AppManagement
        {
            get
            {
                return ResourceManager.GetString("AppManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string AppName
        {
            get
            {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string AppNameSuffixText
        {
            get
            {
                return ResourceManager.GetString("AppNameSuffixText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UI.KIT.
        /// </summary>
        public static string AppNameText
        {
            get
            {
                return ResourceManager.GetString("AppNameText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string AppVersion
        {
            get
            {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure
        {
            get
            {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom Theme.
        /// </summary>
        public static string CustomTheme
        {
            get
            {
                return ResourceManager.GetString("CustomTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string DarkTheme
        {
            get
            {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard
        {
            get
            {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation
        {
            get
            {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device
        {
            get
            {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        public static string DeviceId
        {
            get
            {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enterprise Theme.
        /// </summary>
        public static string EnterpriseTheme
        {
            get
            {
                return ResourceManager.GetString("EnterpriseTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string LightTheme
        {
            get
            {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Section Title.
        /// </summary>
        public static string MenuCategory1Name
        {
            get
            {
                return ResourceManager.GetString("MenuCategory1Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to no longer.
        /// </summary>
        public static string NoLonger
        {
            get
            {
                return ResourceManager.GetString("NoLonger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Now
        {
            get
            {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Okay
        {
            get
            {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        public static string Os
        {
            get
            {
                return ResourceManager.GetString("Os", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OS Version.
        /// </summary>
        public static string OsVersion
        {
            get
            {
                return ResourceManager.GetString("OsVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme
        {
            get
            {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
